s_pPathGrossini       = "grossini.png"
s_pPathSister1        = "grossinis_sister1.png"
s_pPathSister2        = "grossinis_sister2.png"
s_pPathB1             = "b1.png"
s_pPathB2             = "b2.png"
s_pPathR1             = "r1.png"
s_pPathR2             = "r2.png"
s_pPathF1             = "f1.png"
s_pPathF2             = "f2.png"
s_pPathBlock          = "blocks.png"
s_back                = "background.png"
s_back1               = "background1.png"
s_back2               = "background2.png"
s_back3               = "background3.png"
s_stars1              = "stars.png"
s_stars2              = "stars2.png"
s_fire                = "fire.png"
s_snow                = "snow.png"
s_streak              = "streak.png"
s_PlayNormal          = "btn-play-normal.png"
s_PlaySelect          = "btn-play-selected.png"
s_AboutNormal         = "btn-about-normal.png"
s_AboutSelect         = "btn-about-selected.png"
s_HighNormal          = "btn-highscores-normal.png"
s_HighSelect          = "btn-highscores-selected.png"
s_Ball                = "ball.png"
s_Paddle              = "paddle.png"
s_pPathClose          = "close.png"
s_MenuItem            = "menuitemsprite.png"
s_SendScore           = "SendScoreButton.png"
s_PressSendScore      = "SendScoreButtonPressed.png"
s_Power               = "powered.png"
s_AtlasTest           = "atlastest.png"

-- tilemaps resource
s_TilesPng            = "tiles.png"
s_LevelMapTga         = "levelmap.tga"

-- spine test resource
s_pPathSpineBoyJson       = "spineboy.json"
s_pPathSpineBoyAtlas       = "spineboy.atlas"

-- fonts resource
s_markerFeltFontPath   = "fonts/Marker Felt.ttf"
s_arialPath            = "fonts/Marker Felt.ttf"
s_thonburiPath         = "fonts/Marker Felt.ttf"
s_tahomaPath           = "fonts/Marker Felt.ttf"
